name: fwix
channels:
  - conda-forge
  - nvidia/label/cuda-12.4.1
dependencies:
  - cuda-toolkit
  - cuda-nvcc
  - libopencv
  - zfp

  - python=3.11
  - compilers
  - pybind11==2.13.6

  - make
  - cmake==3.25
  - ninja
  - git

  - boost-cpp
  - fftw
  - tbb
  - tbb-devel
  - openssl            
  - flex    
  - libtirpc           

  - scikit-build-core
  - pip
  - patchelf
  - pip:
      - git+https://github.com/arustamm/pysep3d.git@main  # TODO add the version tag when stable

  - numpy
  - pytest
  - scipy
  - numba
  - h5py
  - pyproximal

  - dask=2025.1.0
  - dask-jobqueue=0.9.0
  - distributed==2025.1.0
  - dask-labextension

  - holoviews
  - jupyterlab
  - jupyterlab-nvdashboard

